version: "1"
rules:                      # Array of rules
  - base: upstream_master   # Required. Target branch
    upstream: s-nakaoka:master    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: upstream_release-1.7   # Required. Target branch
    upstream: s-nakaoka:release-1.7    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
